// Demo data for previewing the site without a Supabase connection
// Remove this file once real data is connected

export const demoCategories = [
  { id: "cat-1", name: "Ensino Fundamental I", slug: "fundamental-1", description: "1o ao 5o ano", sort_order: 1 },
  { id: "cat-2", name: "Ensino Fundamental II", slug: "fundamental-2", description: "6o ao 9o ano", sort_order: 2 },
  { id: "cat-3", name: "Ensino Medio", slug: "ensino-medio", description: "1a a 3a serie", sort_order: 3 },
  { id: "cat-4", name: "Educacao Infantil", slug: "infantil", description: "Pre-escola", sort_order: 4 },
];

export const demoProducts = [
  {
    id: "prod-1",
    category_id: "cat-1",
    name: "Kit Escolar Completo — Colegio Santo Agostinho 3o Ano",
    slug: "kit-santo-agostinho-3-ano",
    description: "Kit completo com todos os livros didaticos, cadernos, material de arte e papelaria para o 3o ano do Colegio Santo Agostinho. Inclui 12 livros, 6 cadernos, estojo completo e material de arte.",
    school_name: "Colegio Santo Agostinho",
    grade: "3o Ano — Fund. I",
    price_cents: 89900,
    compare_price_cents: 119900,
    stock: 23,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Livro de Matematica — Buriti Plus", qty: 1 },
      { name: "Livro de Portugues — Buriti Plus", qty: 1 },
      { name: "Livro de Ciencias — Buriti Plus", qty: 1 },
      { name: "Livro de Historia — Buriti Plus", qty: 1 },
      { name: "Livro de Geografia — Buriti Plus", qty: 1 },
      { name: "Caderno brochura 96 folhas", qty: 4 },
      { name: "Caderno de desenho 48 folhas", qty: 2 },
      { name: "Lapis de cor 24 cores Faber-Castell", qty: 1 },
      { name: "Canetinha 12 cores Faber-Castell", qty: 1 },
      { name: "Cola branca 90g", qty: 2 },
      { name: "Tesoura sem ponta", qty: 1 },
      { name: "Borracha branca", qty: 2 },
      { name: "Apontador com deposito", qty: 1 },
      { name: "Lapis grafite HB", qty: 4 },
      { name: "Regua 30cm", qty: 1 },
    ],
    categories: { name: "Ensino Fundamental I", slug: "fundamental-1" },
    created_at: "2026-01-15T10:00:00Z",
  },
  {
    id: "prod-2",
    category_id: "cat-1",
    name: "Kit Escolar Completo — Colegio Bandeirantes 5o Ano",
    slug: "kit-bandeirantes-5-ano",
    description: "Kit completo para o 5o ano do Colegio Bandeirantes. Todos os livros da lista oficial, cadernos e material de papelaria.",
    school_name: "Colegio Bandeirantes",
    grade: "5o Ano — Fund. I",
    price_cents: 109900,
    compare_price_cents: 149900,
    stock: 15,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Livro de Matematica — BNCC Atualizado", qty: 1 },
      { name: "Livro de Portugues — BNCC Atualizado", qty: 1 },
      { name: "Livro de Ingles — Way to English", qty: 1 },
      { name: "Caderno universitario 200 folhas", qty: 3 },
    ],
    categories: { name: "Ensino Fundamental I", slug: "fundamental-1" },
    created_at: "2026-01-14T10:00:00Z",
  },
  {
    id: "prod-3",
    category_id: "cat-2",
    name: "Kit Escolar — Colegio Objetivo 7o Ano",
    slug: "kit-objetivo-7-ano",
    description: "Material escolar completo para o 7o ano do Colegio Objetivo. Apostilas, cadernos, material de geometria e papelaria.",
    school_name: "Colegio Objetivo",
    grade: "7o Ano — Fund. II",
    price_cents: 129900,
    compare_price_cents: 159900,
    stock: 8,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Apostila Objetivo — 1o Semestre", qty: 1 },
      { name: "Apostila Objetivo — 2o Semestre", qty: 1 },
      { name: "Kit geometria (compasso, esquadros, transferidor)", qty: 1 },
    ],
    categories: { name: "Ensino Fundamental II", slug: "fundamental-2" },
    created_at: "2026-01-13T10:00:00Z",
  },
  {
    id: "prod-4",
    category_id: "cat-2",
    name: "Kit Escolar — Escola Stance Dual 8o Ano",
    slug: "kit-stance-dual-8-ano",
    description: "Kit bilingue completo para o 8o ano da Escola Stance Dual. Inclui livros em portugues e ingles.",
    school_name: "Escola Stance Dual",
    grade: "8o Ano — Fund. II",
    price_cents: 159900,
    compare_price_cents: null,
    stock: 12,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Livro de Matematica — Bilingue", qty: 1 },
      { name: "Livro de Science — Cambridge", qty: 1 },
    ],
    categories: { name: "Ensino Fundamental II", slug: "fundamental-2" },
    created_at: "2026-01-12T10:00:00Z",
  },
  {
    id: "prod-5",
    category_id: "cat-3",
    name: "Kit Ensino Medio — Colegio Etapa 1a Serie",
    slug: "kit-etapa-1-serie",
    description: "Kit completo para a 1a serie do Ensino Medio no Colegio Etapa. Apostilas, cadernos e material de laboratorio.",
    school_name: "Colegio Etapa",
    grade: "1a Serie — EM",
    price_cents: 189900,
    compare_price_cents: 229900,
    stock: 4,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Apostila Etapa — Volume 1", qty: 1 },
      { name: "Apostila Etapa — Volume 2", qty: 1 },
      { name: "Caderno universitario 10 materias", qty: 2 },
    ],
    categories: { name: "Ensino Medio", slug: "ensino-medio" },
    created_at: "2026-01-11T10:00:00Z",
  },
  {
    id: "prod-6",
    category_id: "cat-4",
    name: "Kit Infantil — Colegio Pueri Domus Pre II",
    slug: "kit-pueri-domus-pre-2",
    description: "Kit de material escolar para a Educacao Infantil Pre II. Material ludico, livros de atividades, massinha e material de arte.",
    school_name: "Colegio Pueri Domus",
    grade: "Pre II — Infantil",
    price_cents: 59900,
    compare_price_cents: 79900,
    stock: 30,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Livro de Atividades — Pre II", qty: 1 },
      { name: "Massinha Play-Doh 6 cores", qty: 1 },
      { name: "Giz de cera grosso 12 cores", qty: 1 },
      { name: "Tinta guache 6 cores", qty: 1 },
    ],
    categories: { name: "Educacao Infantil", slug: "infantil" },
    created_at: "2026-01-10T10:00:00Z",
  },
  {
    id: "prod-7",
    category_id: "cat-1",
    name: "Kit Escolar — Colegio Dante Alighieri 2o Ano",
    slug: "kit-dante-2-ano",
    description: "Kit completo para o 2o ano do Colegio Dante Alighieri. Livros, cadernos e todo material de papelaria.",
    school_name: "Colegio Dante Alighieri",
    grade: "2o Ano — Fund. I",
    price_cents: 84900,
    compare_price_cents: 99900,
    stock: 18,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Livro de Alfabetizacao", qty: 1 },
      { name: "Livro de Matematica", qty: 1 },
      { name: "Caderno brochura 48 folhas", qty: 4 },
    ],
    categories: { name: "Ensino Fundamental I", slug: "fundamental-1" },
    created_at: "2026-01-09T10:00:00Z",
  },
  {
    id: "prod-8",
    category_id: "cat-3",
    name: "Kit Ensino Medio — Colegio Vértice 2a Serie",
    slug: "kit-vertice-2-serie",
    description: "Kit completo para a 2a serie do Ensino Medio no Colegio Vertice. Preparacao ENEM inclusa.",
    school_name: "Colegio Vertice",
    grade: "2a Serie — EM",
    price_cents: 199900,
    compare_price_cents: null,
    stock: 3,
    is_active: true,
    image_urls: [
      "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=400&fit=crop",
    ],
    items_list: [
      { name: "Apostila Vertice — Integral", qty: 1 },
      { name: "Caderno ENEM — Questoes", qty: 1 },
    ],
    categories: { name: "Ensino Medio", slug: "ensino-medio" },
    created_at: "2026-01-08T10:00:00Z",
  },
];
